services:
  app:
    build:
      context: .
      args:
        http_proxy: http://172.31.2.4:8080
        https_proxy: http://172.31.2.4:8080
        no_proxy: localhost,127.0.0.1
    ports:
      - "8000:8000"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
